server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-clients
    username: postgres
    password: felipeb222
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/