apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-clients-deployment
  labels:
    app: ms-clients-deployment
spec:
  selector:
    matchLabels:
        app: ms-clients-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-clients-pod
    spec:
        containers:
            - name: ms-clients
              image: felipeb2001/ms-clients
              ports:
                - containerPort: 8091
              env:
                - name: SERVER_PORT
                  value: "8091"
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config-map
                      key: DB_HOST_CLIENTS
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config-map
                      key: DB_PORT_CLIENTS
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config-map
                      key: DB_NAME_CLIENTS
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: DB_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ms-clients-service
  labels:
    app: ms-clients-service
spec:
    selector:
        app: ms-clients-pod
    ports:
      - protocol: TCP
        port: 8091
        targetPort: 8091
    type: LoadBalancer
