apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_CLIENTS: clients-db-service
  DB_PORT_CLIENTS: "5432"
  DB_NAME_CLIENTS: ms_clients
  DB_HOST_CREDIT_EVALUATION: creditEvaluation-db-service
  DB_PORT_CREDIT_EVALUATION: "5432"
  DB_NAME_CREDIT_EVALUATION: ms_credit_evaluation
  DB_HOST_CREDIT_REQUEST: creditRequest-db-service
  DB_PORT_CREDIT_REQUEST: "5432"
  DB_NAME_CREDIT_REQUEST: ms_credit_request
