apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_CLIENTS: clients-db-service
  DB_PORT_CLIENTS: "5432"
  DB_NAME_CLIENTS: clients-db