apiVersion: v1
kind: PersistentVolume
metadata:
  name: request-tracking-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/request-tracking-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: request-tracking-db-pvc
  labels:
    app: postgres
    tier: database
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-tracking-db-deployment
  labels:
    app: request-tracking-db-deployment
    tier: database
spec:
    selector:
      matchLabels:
        app: request-tracking-db-deployment
    strategy:
        type: Recreate
    template:
      metadata:
        labels:
            app: request-tracking-db-deployment
            tier: database
      spec:
        containers:
        - name: request-tracking-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: request-tracking-db-data
        volumes:
          - name: request-tracking-db-data
            persistentVolumeClaim:
              claimName: request-tracking-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: request-tracking-db-service
  labels:
    app: request-tracking-db-service
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: request-tracking-db-deployment
    tier: database
    type: LoadBalancer